// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlhrkggczxszxbwgreyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsaHJrZ2djenhzenhid2dyZXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQxMDksImV4cCI6MjA2NTU5MDEwOX0.vvS1hnAiA0X5Gde32TBZ66jG5EEOw1MelNqzEWvw3mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);